### PR TITLE
Add github action: publish to pypi

### PR DESCRIPTION
**Pull request by yanoom**
New action uses a dedicated docker container with Poetry.
It builds the package and pushes it to pypi.org.
Add version badge to README.md (+switched coverage badge to shields.io)

### CODE REVIEW

**Comment by MatanRubin** [comment]
Please make sure:

1. We can only run "publish" from `master`
2. "publish" is a manual action

**Comment by yanoom** [comment]
+ Verify Pypi returns error when publishing **same version** again

**Comment by yanoom** [comment]
>     2. "publish" is a manual action

As far as I see (like we've discussed), I don't see the option to trigger the workflow manually built-in.
**I suggest** we use Github's "release" feature with:
```
on:
  release:
    types: [published]
```
https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release

Seams like a good (and correct) solution to me (also solves the first requirement)...
**2 more possible solutions, which I'm not in favor of:**

---
There is this 3rd party tool which looks nice:
https://www.actionspanel.app/

---
There is also the option to trigger "repository_dispatch" with an HTTP-POST request:
https://goobar.io/2019/12/07/manually-triggering-github-actions-workflows-using-postman/

**Comment by yanoom** [comment]
Verified "re-publish" (same version) fails:
image

**Pull request merged**
